// <auto-generated />
namespace resource_server.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class refreshtoken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refreshtoken));
        
        string IMigrationMetadata.Id
        {
            get { return "201901031833077_refreshtoken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
